language: cpp
sudo: true

os:
  - linux
  - osx

cache:
  directories:
    - $TRAVIS_BUILD_DIR/CMake
    - $TRAVIS_BUILD_DIR/glm
    - $TRAVIS_BUILD_DIR/flatbuffers
    - $TRAVIS_BUILD_DIR/glfw
    - ~/.cache/pip
    - ~/Library/Caches/Homebrew
    - $TRAVIS_BUILD_DIR/.scons_cache

compiler: gcc

env:
  - DOUBLES=no TARGET=debug MULTITHREAD=no
  - DOUBLES=yes TARGET=debug MULTITHREAD=no
  - DOUBLES=no TARGET=release MULTITHREAD=no
  - DOUBLES=no TARGET=release MULTITHREAD=yes

# Travis CI's Windows Environment times out, so we can't use it yet
# matrix:
#   include:
#     - env: DOUBLES=no
#       os: windows
#       compiler: msvc
#     - env: DOUBLES=yes
#       os: windows
#       compiler: msvc
#       filter_secrets: false

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export HOMEBREW_NO_AUTO_UPDATE=1;
      brew install scons;
    else
      python -m pip install scons --user;
      sudo apt-get -y install xorg-dev libglu1-mesa-dev;
    fi
  - git clone https://github.com/g-truc/glm --branch stable || true
  - cd glm
  - git pull origin stable
  - cd ..
  - git clone https://github.com/google/flatbuffers || true
  - cd flatbuffers
  - git pull
  - cd ..
  - git clone https://github.com/glfw/glfw --branch 3.3-stable || true
  - cd glfw
  - git pull origin 3.3-stable
  - cd ..
  - mkdir CMake || true
  - cd CMake
  - mkdir glm || true
  - mkdir flatbuffers || true
  - mkdir glfw || true
  - cd glm
  - cmake -D GLM_TEST_ENABLE:BOOL=0 $TRAVIS_BUILD_DIR/glm
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      msbuild INSTALL.vcxproj;
    else
      sudo make install all;
    fi
  - cd ..
  - cd flatbuffers
  - cmake -D FLATBUFFERS_BUILD_TESTS:BOOL=0 $TRAVIS_BUILD_DIR/flatbuffers
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      msbuild INSTALL.vcxproj;
    else
      sudo make install all;
    fi
  - cd ..
  - cd glfw
  - cmake -DGLFW_BUILD_DOCS:BOOL=0 -DGLFW_BUILD_TESTS:BOOL=0 -DGLFW_BUILD_EXAMPLES:BOOL=0 $TRAVIS_BUILD_DIR/glfw
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      msbuild INSTALL.vcxproj;
    else
      sudo make install all;
    fi
  - cd $TRAVIS_BUILD_DIR

script:
  - scons -j2 build_type=tests target=$TARGET use_doubles=$DOUBLES cache=$TRAVIS_BUILD_DIR/.scons_cache multithreading=$MULTITHREAD
  - sh "$TRAVIS_BUILD_DIR/test/bin/run_unit_tests.sh"