language: cpp
sudo: true

os:
  - linux
  - osx

cache:
  directories:
    - $TRAVIS_BUILD_DIR/CMake
    - $TRAVIS_BUILD_DIR/glm
    - $TRAVIS_BUILD_DIR/flatbuffers

compiler: gcc

env:
  - DOUBLES=no
  - DOUBLES=yes

# Travis CI's Windows Environment times out, so we can't use it yet
# matrix:
#   include:
#     - env: DOUBLES=no
#       os: windows
#       compiler: msvc
#     - env: DOUBLES=yes
#       os: windows
#       compiler: msvc
#       filter_secrets: false

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export HOMEBREW_NO_AUTO_UPDATE=1;
      brew install scons;
    else
      python -m pip install scons --user;
    fi
  - git clone https://github.com/g-truc/glm || true
  - git clone https://github.com/google/flatbuffers || true
  - mkdir CMake || true
  - cd CMake
  - mkdir glm || true
  - mkdir flatbuffers || true
  - cd glm
  - cmake -D GLM_TEST_ENABLE:BOOL=0 $TRAVIS_BUILD_DIR/glm
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      msbuild INSTALL.vcxproj;
    else
      sudo make install all;
    fi
  - cd ..
  - cd flatbuffers
  - cmake -D FLATBUFFERS_BUILD_TESTS:BOOL=0 $TRAVIS_BUILD_DIR/flatbuffers
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      msbuild INSTALL.vcxproj;
    else
      sudo make install all;
    fi
  - cd $TRAVIS_BUILD_DIR

script:
  scons -j2 build_type=test use_doubles=$DOUBLES

after_script:
  - $TRAVIS_BUILD_DIR/test/bin/tool_serialize_test # serialize
  - $TRAVIS_BUILD_DIR/test/bin/tool_serialize_test # serialize & deserialize
  - $TRAVIS_BUILD_DIR/test/bin/cell_serialize_test # serialize
  - $TRAVIS_BUILD_DIR/test/bin/cell_serialize_test # serialize & deserialize
  - $TRAVIS_BUILD_DIR/test/bin/ellipsoid_test # value test