language: cpp
sudo: true

os:
  - linux
  - osx

cache:
  directories:
    - $TRAVIS_BUILD_DIR/CMake
    - $TRAVIS_BUILD_DIR/glm
    - $TRAVIS_BUILD_DIR/flatbuffers
    - ~/.cache/pip
    - ~/Library/Caches/Homebrew
    - $TRAVIS_BUILD_DIR/.scons_cache

compiler: gcc

env:
  - TARGET=debug
  - TARGET=release

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export HOMEBREW_NO_AUTO_UPDATE=1;
      brew install scons;
    else
      python -m pip install scons --user;
      sudo apt-get -y install xorg-dev libglu1-mesa-dev;
    fi
  - git clone https://github.com/g-truc/glm --branch stable || true
  - cd glm
  - git pull origin stable
  - cd ..
  - git clone https://github.com/google/flatbuffers || true
  - cd flatbuffers
  - git pull
  - cd ..
  - mkdir CMake || true
  - cd CMake
  - mkdir glm || true
  - mkdir flatbuffers || true
  - cd glm
  - cmake -D GLM_TEST_ENABLE:BOOL=0 $TRAVIS_BUILD_DIR/glm
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      msbuild INSTALL.vcxproj;
    else
      sudo make install all;
    fi
  - cd ..
  - cd flatbuffers
  - cmake -D FLATBUFFERS_BUILD_TESTS:BOOL=0 $TRAVIS_BUILD_DIR/flatbuffers
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      msbuild INSTALL.vcxproj;
    else
      sudo make install all;
    fi
  - cd $TRAVIS_BUILD_DIR

script:
  - scons -j2 build_type=tests target=$TARGET cache=$TRAVIS_BUILD_DIR/.scons_cache
  - sh "$TRAVIS_BUILD_DIR/test/bin/run_unit_tests.sh"